https://www.linkedin.com/in/latha-t-k-b21018128/


https://github.com/Premalatha-success

https://www.youtube.com/@datasciencemonster3703

# My first Program

### My first Program

#### My first Program

###### hfhajsfkhdkjhd

In [1]:
print("Hello World")

Hello World


In [2]:
#### Print ur name
print("Latha")

Latha


In [5]:
Print("Latha") ### Python is case-sensitive

NameError: name 'Print' is not defined

In [6]:
print(latha) ### string should be enclosed with "" or ''

NameError: name 'latha' is not defined

In [7]:
print(1)

1


In [8]:
print('latha')

latha


### Data Types

In [9]:
a=10
type(a) ### int->integer(no. without decimal point)

int

In [10]:
b=10.5
type(b) ### float->number with a decimal point

float

In [11]:
c="Python"
type(c) ### str->string(text/object)

str

In [12]:
d=True
type(d) ### bool->boolean(True and False)

bool

In [13]:
e=false
type(e) ### It should be False

NameError: name 'false' is not defined

In [14]:
f="True"
type(f)

str

In [15]:
### Variables
x=10
x # xis variable

10

In [16]:
sample_list=[1,2,3,3,6]
sample_list

[1, 2, 3, 3, 6]

In [17]:
sample data=1,2,3
sample data # space is not allowed

SyntaxError: invalid syntax (2079876364.py, line 1)

In [18]:
2sample=1,2,3,4
2sample

SyntaxError: invalid decimal literal (2535379369.py, line 1)

In [19]:
s2ample=1,2,3,4
s2ample # Variable name should not start with a number

(1, 2, 3, 4)

In [21]:
sample+data=1,2,3,4
sample+data ### Variable names donot allow any spl char other than _

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (1259289647.py, line 1)

#### Variable names can start with A-Z,a-z or _
#### Variable names should not start with a number
#### Variable name should not have space
#### Variable names don't allow any special chars other than _

In [25]:
x=10
print(type(x))
print(x)

<class 'int'>
10


### String

In [70]:
str1="Hello Python"
str1

'Hello Python'

In [27]:
str1="Hello Python'
str1

SyntaxError: unterminated string literal (detected at line 1) (3439460991.py, line 1)

In [28]:
str1="""Hello World"""
str1   ### Multiple lines """"""

'Hello World'

In [29]:
str1[0]

'H'

In [30]:
str1[5]

' '

In [31]:
str1[6]

'W'

In [32]:
str1[100]

IndexError: string index out of range

In [34]:
str1[10]

IndexError: string index out of range

In [35]:
str1[-1]

'd'

In [36]:
str1[-11]

'H'

In [37]:
str1[-12]

IndexError: string index out of range

In [38]:
len(str1)

11

In [39]:
str1[0:4] #slicing

'Hell'

In [40]:
str1[0:5]

'Hello'

In [41]:
str1[6:11]

'World'

In [ ]:
### Retrieve World with negative index

In [43]:
str1[-6:-1]

' Worl'

In [45]:
str1[-5:]

'World'

In [46]:
str1[0:5]

'Hello'

In [47]:
str1[0:]

'Hello World'

### Update a string using index

In [48]:
str1[0:5]="HELLO"

TypeError: 'str' object does not support item assignment

In [ ]:
#### Delete a string

del str1

In [50]:
str1

NameError: name 'str1' is not defined

### string concatenation

In [51]:
first_name="Prema"
last_name="Latha"
full_name=first_name+last_name
full_name

'PremaLatha'

In [54]:
first_name="Prema"
last_name="Latha"
full_name=first_name+" "+last_name
full_name

'Prema Latha'

### Iterating through a string

In [55]:
for i in full_name:
    print(i)

P
r
e
m
a
 
L
a
t
h
a


In [ ]:
### String Membership

In [56]:
"a" in full_name

True

In [57]:
"k" in full_name

False

In [58]:
full_name.strip()

'Prema Latha'

In [59]:
full_name="      Premalatha   " ### Removes whitespace
full_name.strip()

'Premalatha'

In [60]:
full_name="      Prema  latha   " 
full_name.strip()

'Prema  latha'

In [61]:
full_name.rstrip()

'      Prema  latha'

In [62]:
full_name.lstrip()

'Prema  latha   '

In [64]:
str2="***********Hello Everyone!!!!***********All the Best*****"
str2.strip('*')

'Hello Everyone!!!!***********All the Best'

In [65]:
str2.lstrip('*')

'Hello Everyone!!!!***********All the Best*****'

In [67]:
str2.rstrip('*')

'***********Hello Everyone!!!!***********All the Best'

In [71]:
str1.lower()

'hello python'

In [72]:
str1.upper()

'HELLO PYTHON'

In [73]:
str3="welcome to the session"
str3.title()

'Welcome To The Session'

In [74]:
str1

'Hello Python'

In [75]:
str1.replace("Hello","Hallo")

'Hallo Python'

In [76]:
str1.replace("Python","Java")

'Hello Java'

In [77]:
str4="one two three one two one three four one"
len(str4)

40

In [78]:
str4.count("one")

4

In [79]:
str4.count("five")

0

In [80]:
"three" in str4

True

In [81]:
"five" in str4

False

In [82]:
for i in str4:
    print(i)

o
n
e
 
t
w
o
 
t
h
r
e
e
 
o
n
e
 
t
w
o
 
o
n
e
 
t
h
r
e
e
 
f
o
u
r
 
o
n
e


In [83]:
str4.startswith("one")

True

In [85]:
str4.endswith("five")

False

In [86]:
str4.split()

['one', 'two', 'three', 'one', 'two', 'one', 'three', 'four', 'one']

In [92]:
str5="welcome Everyone"
str5.center(100)

'                                          welcome Everyone                                          '

In [93]:
str5.rjust(100)

'                                                                                    welcome Everyone'

In [94]:
str5.ljust(100)

'welcome Everyone                                                                                    '

In [95]:
"one" in str5

True

In [96]:
str5.find("one")

13

In [97]:
str5.index("one")

13

### List

In [ ]:
### heterogenous->allow multiple data types
### Square bracket
### Retrieved using index
### List is mutable(change is accepted)

In [98]:
list1=[12,25,12.87,True,"python","sql"]
list1

[12, 25, 12.87, True, 'python', 'sql']

In [99]:
list1[0]

12

In [100]:
list1[5]

'sql'

In [101]:
list1[15]

IndexError: list index out of range

In [103]:
list1[4:]

['python', 'sql']

In [105]:
list1[4:6]

['python', 'sql']

In [106]:
list1[-2:]

['python', 'sql']

In [107]:
list1[:-2]

[12, 25, 12.87, True]

In [109]:
### nested list
list2=["Python",25,[31,21.8,False]]
list2

['Python', 25, [31, 21.8, False]]

In [110]:
type(list2)

list

In [111]:
len(list1)

6

In [112]:
len(list2)

3

In [114]:
list2[2][0]

31

In [115]:
list2[-1][-1]

False

In [116]:
list2.add(10)

AttributeError: 'list' object has no attribute 'add'

In [117]:
list2.append(10)

In [118]:
list2

['Python', 25, [31, 21.8, False], 10]

In [119]:
list2.append(1)

In [120]:
list2

['Python', 25, [31, 21.8, False], 10, 1]

In [122]:
list2.insert(2,22.7)

In [123]:
list2

['Python', 25, 22.7, [31, 21.8, False], 10, 1]

In [125]:
list2.remove(10)

In [126]:
list2

['Python', 25, 22.7, [31, 21.8, False], 1]

In [127]:
list2.pop()

1

In [128]:
list2

['Python', 25, 22.7, [31, 21.8, False]]

In [129]:
list2.pop()
list2

['Python', 25, 22.7]

In [130]:
### list2.remove(22.7)
list2.pop(2)

22.7

In [131]:
list2

['Python', 25]

In [132]:
list1

[12, 25, 12.87, True, 'python', 'sql']

In [133]:
list1[0]=13

In [134]:
list1

[13, 25, 12.87, True, 'python', 'sql']

In [135]:
del list2

In [136]:
list2

NameError: name 'list2' is not defined

In [137]:
list1

[13, 25, 12.87, True, 'python', 'sql']

In [138]:
list3=list1.copy()
list3

[13, 25, 12.87, True, 'python', 'sql']

In [140]:
list4=list1+list3

In [141]:
list4

[13, 25, 12.87, True, 'python', 'sql', 13, 25, 12.87, True, 'python', 'sql']

In [147]:
list1.extend(list3)

In [153]:
list1

[13,
 25,
 12.87,
 True,
 'python',
 'sql',
 13,
 25,
 12.87,
 True,
 'python',
 'sql',
 13,
 25,
 12.87,
 True,
 'python',
 'sql',
 13,
 25,
 12.87,
 True,
 'python',
 'sql',
 13,
 25,
 12.87,
 True,
 'python',
 'sql']

In [149]:
"python" in list1

True

In [151]:
"one" in list1

False

In [152]:
if "python" in list1:
    print("There is python in the list")
else:
    print("There is no python word in the list")

There is python in the list


In [154]:
list1

[13,
 25,
 12.87,
 True,
 'python',
 'sql',
 13,
 25,
 12.87,
 True,
 'python',
 'sql',
 13,
 25,
 12.87,
 True,
 'python',
 'sql',
 13,
 25,
 12.87,
 True,
 'python',
 'sql',
 13,
 25,
 12.87,
 True,
 'python',
 'sql']

In [155]:
### Reverse this list
list1=[10,20,30,21,41,79]
list1

[10, 20, 30, 21, 41, 79]

In [156]:
list1.reverse()

In [157]:
list1

[79, 41, 21, 30, 20, 10]

In [158]:
list1.sort()

In [159]:
list1

[10, 20, 21, 30, 41, 79]

In [160]:
list1.sort(reverse=True)

In [161]:
list1

[79, 41, 30, 21, 20, 10]

In [162]:
list1

[79, 41, 30, 21, 20, 10]

In [163]:
list1[::-1] #reverse the list

[10, 20, 21, 30, 41, 79]

In [164]:
for i in list1:
    print(i)

79
41
30
21
20
10


In [165]:
list1.count(10)

1

In [166]:
list3=[10,20,30,21,41,79,"Python","pyspark"]

In [167]:
list3.sort()

TypeError: '<' not supported between instances of 'str' and 'int'

In [168]:
list4=["sql","java","Python","pyspark"]
list4.sort()

In [169]:
list4

['Python', 'java', 'pyspark', 'sql']

### Tuple

In [ ]:
#### Paranthesis or without any brackets
#### immutable
#### heterogenous
#### retrieve it using index

In [182]:
tuple1=(10,29,52,26.8)
tuple1

(10, 29, 52, 26.8)

In [171]:
type(tuple1)

tuple

In [172]:
tuple2=10,29,52,26.8
tuple2

(10, 29, 52, 26.8)

In [173]:
type(tuple2)

tuple

In [174]:
tuple2[0]

10

In [175]:
tuple2[0:2]

(10, 29)

In [176]:
10 in tuple1


True

In [177]:
tuple1.reverse()

AttributeError: 'tuple' object has no attribute 'reverse'

In [178]:
tuple1.sort()

AttributeError: 'tuple' object has no attribute 'sort'

In [179]:
tuple1.sort(reverse=True)

AttributeError: 'tuple' object has no attribute 'sort'

In [180]:
del tuple1

In [181]:
tuple1

NameError: name 'tuple1' is not defined

In [183]:
tuple1[0]=100

TypeError: 'tuple' object does not support item assignment

In [185]:
for i in tuple1:
    print (i)

10
29
52
26.8


In [186]:
tuple1.count(10)

1

In [187]:
tuple1.index(10)

0

In [188]:
sample=list(tuple1)
sample

[10, 29, 52, 26.8]

In [189]:
sample1=tuple(sample)
sample1

(10, 29, 52, 26.8)

In [ ]:
### Self-Assessment1: https://github.com/Premalatha-success/syn_python_jan_25/blob/main/string_exercise.docx


In [ ]:
o	Write a Python code to check if the word "learn" is in the sentence "Let's all learn Python!".
o	Convert the string "hello world" to uppercase.
o	Concatenate two strings: "Data" and "Analysis".
o	Replace all occurrences of "a" with "@" in the string "DataAnalytics".
o	Write a Python code to reverse the string "Python".
o	Count how many times the letter "e" appears in the string "Experience".
o	Split the string "Learn,Analyze,Build" into a list of words.
o	Create a string variable with your full name.
o	What is the length of the string "PythonProgramming"?
o	How would you extract the first three characters of the string "DataScience"?


### Dictionary

In [ ]:
mylist=["one","two","three",1,2,3]

In [ ]:
mytup="one","two","three",1,2,3

In [190]:
mydict={1:"one",2:"two",3:"three"}

In [ ]:
#### {}
#### key-value pairs
#### key is unique
#### values can be duplicated
#### Value can be retrieved using key

In [191]:
mydict

{1: 'one', 2: 'two', 3: 'three'}

In [192]:
mydict={"one":"A",2:"two",3:"three"}

In [193]:
mydict.keys()

dict_keys(['one', 2, 3])

In [194]:
mydict.values()

dict_values(['A', 'two', 'three'])

In [195]:
mydict.items()

dict_items([('one', 'A'), (2, 'two'), (3, 'three')])

In [198]:
mydict1={1:"one",2:"two",3:"three",4:"hi",2:"hello",3:"news",8:"one"}
mydict1

{1: 'one', 2: 'hello', 3: 'news', 4: 'hi', 8: 'one'}

In [199]:
mydict1[0]

KeyError: 0

In [200]:
mydict1[1]

'one'

In [201]:
mydict1[4]

'hi'

In [202]:
dict={1:"one",2:"two","C":["latha","pds",39,166000],4:("Apple","Bat","Cat"),"d":{"Name":"Prem","Age":"42"}}
dict

{1: 'one',
 2: 'two',
 'C': ['latha', 'pds', 39, 166000],
 4: ('Apple', 'Bat', 'Cat'),
 'd': {'Name': 'Prem', 'Age': '42'}}

In [203]:
dict.keys()

dict_keys([1, 2, 'C', 4, 'd'])

In [204]:
dict.values()

dict_values(['one', 'two', ['latha', 'pds', 39, 166000], ('Apple', 'Bat', 'Cat'), {'Name': 'Prem', 'Age': '42'}])

In [206]:
dict.items()

dict_items([(1, 'one'), (2, 'two'), ('C', ['latha', 'pds', 39, 166000]), (4, ('Apple', 'Bat', 'Cat')), ('d', {'Name': 'Prem', 'Age': '42'})])

In [ ]:
### Adding a simple key-value pair

In [207]:
dict["DOB"]=2014
dict["Place"]="Chennai"
dict

{1: 'one',
 2: 'two',
 'C': ['latha', 'pds', 39, 166000],
 4: ('Apple', 'Bat', 'Cat'),
 'd': {'Name': 'Prem', 'Age': '42'},
 'DOB': 2014,
 'Place': 'Chennai'}

In [208]:
dict1={"DOB":2004}
dict.update(dict1)
dict

{1: 'one',
 2: 'two',
 'C': ['latha', 'pds', 39, 166000],
 4: ('Apple', 'Bat', 'Cat'),
 'd': {'Name': 'Prem', 'Age': '42'},
 'DOB': 2004,
 'Place': 'Chennai'}

In [209]:
dict["Job"]="Analyst"
dict

{1: 'one',
 2: 'two',
 'C': ['latha', 'pds', 39, 166000],
 4: ('Apple', 'Bat', 'Cat'),
 'd': {'Name': 'Prem', 'Age': '42'},
 'DOB': 2004,
 'Place': 'Chennai',
 'Job': 'Analyst'}

In [210]:
dict.pop("DOB")

2004

In [211]:
dict

{1: 'one',
 2: 'two',
 'C': ['latha', 'pds', 39, 166000],
 4: ('Apple', 'Bat', 'Cat'),
 'd': {'Name': 'Prem', 'Age': '42'},
 'Place': 'Chennai',
 'Job': 'Analyst'}

In [212]:
dict1=dict.copy()

In [213]:
dict1

{1: 'one',
 2: 'two',
 'C': ['latha', 'pds', 39, 166000],
 4: ('Apple', 'Bat', 'Cat'),
 'd': {'Name': 'Prem', 'Age': '42'},
 'Place': 'Chennai',
 'Job': 'Analyst'}

In [216]:
### Looping
for i in dict1:
    print (i,":",dict1[i])

1 : one
2 : two
C : ['latha', 'pds', 39, 166000]
4 : ('Apple', 'Bat', 'Cat')
d : {'Name': 'Prem', 'Age': '42'}
Place : Chennai
Job : Analyst


In [217]:
"Place" in dict1

True

In [ ]:
Self-Assessment 2

In [ ]:
1.	Create a list of five numbers.
2.	How would you append the number 6 to the list [1, 2, 3, 4, 5]?
3.	How would you access the third element in the list ["apple", "banana", "cherry", "date"]?
4.	Remove the last item from the list [10, 20, 30, 40].
5.	Write a Python code to sort the list [4, 1, 8, 5, 2] in ascending order.
6.	Create a list with mixed data types: an integer, a string, and a floating-point number.
7.	Use list slicing to get the first three elements of the list [10, 20, 30, 40, 50].
8.	Count how many times the number 3 appears in the list [1, 3, 3, 5, 7].
9.	Write a Python code to merge the lists [1, 2] and [3, 4] into one list.
10.	How would you clear all the items in the list ["a", "b", "c", "d"]?


In [ ]:
https://github.com/Premalatha-success/Python_sep_2024/blob/main/Dictionary_exercise.docx
https://github.com/Premalatha-success/Python_sep_2024/blob/main/Tuple_exercise.docx
https://github.com/Premalatha-success/TIAA_batch1_nov/blob/main/Operators_assignment.docx

### Operators

#### Arithmetic operators

In [1]:
5+8

13

In [5]:
3.0+4.0

7.0

In [6]:
5+9.3

14.3

In [7]:
"hello"+"python"

'hellopython'

In [8]:
"hello"+5

TypeError: can only concatenate str (not "int") to str

In [9]:
"hello"+1.0

TypeError: can only concatenate str (not "float") to str

In [11]:
income=1000000
incentive=10000
total_income=income+incentive
total_income

1010000

In [2]:
5-8

-3

In [13]:
"hello"-"lo"

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [3]:
5*8

40

In [14]:
"hello"*"python"

TypeError: can't multiply sequence by non-int of type 'str'

In [15]:
"hello"* 3

'hellohellohello'

In [16]:
"hello"* 3.5

TypeError: can't multiply sequence by non-int of type 'float'

In [4]:
5/8

0.625

#### Implicit conversion->Data type is changed without programmer's intervention

In [17]:
10/2

5.0

In [18]:
3.2/1.6

2.0

In [19]:
6/2.0

3.0

In [20]:
"string"/4

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [21]:
income=100000
incentive="1000"
total=income+incentive
total

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [22]:
total=income+float(incentive)
total

101000.0

In [23]:
total=income+int(incentive)
total

101000

#### In the above ex,I have changed the data type of incentive.Explicit Conversion

In [24]:
5**2 #exponentiation(power)

25

In [25]:
8**7

2097152

In [26]:
10 % 2 ## Modulus

0

In [27]:
10%3

1

In [28]:
10%4

2

In [29]:
10%5

0

In [30]:
10%6

4

In [31]:
2%10

2

In [32]:
3%10

3

In [33]:
7%8

7

#### a % b-> if a >b,it returns remainder,else a

In [34]:
10//2

5

In [35]:
10//3

3

In [36]:
10//4

2

In [37]:
2//10

0

In [38]:
3//10

0

In [39]:
4//10

0

#### a//b-> if a > b it returns quotient else 0

### Relational Operators

In [40]:
tom_age=25
jerry_age=21

In [41]:
tom_age==jerry_age

False

In [42]:
tom_age!=jerry_age

True

In [43]:
tom_age>jerry_age

True

In [44]:
tom_age<jerry_age

False

In [45]:
tom_age>=jerry_age

True

In [46]:
tom_age<=jerry_age

False

### Logical Operators

In [47]:
is_student=True
in_college=True
in_school=False
is_male=False

In [48]:
in_school and is_male

False

In [49]:
is_student and in_college

True

In [50]:
is_student and in_school

False

In [51]:
in_school and is_student

False

In [52]:
in_school or is_male

False

In [53]:
is_student or in_college

True

In [54]:
is_student or in_school

True

In [55]:
not(is_student)

False

In [56]:
not(is_student) or not(in_school)

True

In [59]:
is_sunny=False
has_free_time=True
is_tired=False
is_sunny or has_free_time or is_tired

True

### Membership operator(in)


In [60]:
vowels="aeiou"
"u" in vowels

True

In [61]:
"u" not in vowels

False

In [62]:
"k" not in vowels

True

In [63]:
"A" in vowels

False

### Bitwise Operators

In [5]:
a = 6
b = 3

print(6 & 3) #bitwise and
print(6 | 3) #bitwise or
print(6 ^ 3) #bitwise xor
print(a >> 2) #Zero fill left shift
print(a << 2) #Signed right shift	

2
7
5
1
24


In [ ]:
### Self-Assessment 3
https://github.com/Premalatha-success/TIAA_batch1_nov/blob/main/Operators_assignment.docx

In [ ]:
1.	Given the statements:
o	A = True
o	B = False
o	C = True
Evaluate the following:
(A and B) or (not C and B)
2.	If X = False and Y = True, what is the result of:
not(X or not Y) and (X or Y)?
________________________________________
Multiple Choice:
3.	If P = True, Q = False, and R = True, which of the following evaluates to True?
a. (P or Q) and (not R)
b. not (Q and R) or P
c. (P and not Q) or (Q and R)
d. not (P and R)
4.	Given D = False, E = True, and F = True, what is the value of the expression?
D or (not E and F) and (D or E)
a. True
b. False
c. None
d. Invalid Expression
________________________________________
Fill in the Blanks:
5.	Fill in the blanks to make the following statement True:
(____ and True) or (False and not ____) = True.

6.	If (A and not B) or (C and D) evaluates to False, which of the following must be False?
a. A
b. B
c. C
d. D
________________________________________
Code Interpretation:
7.	What will the following Python code output?
A = True
B = False
C = True
result = A and (not B or C) and not (B and C)
print(result)
8.	Consider the following pseudocode:
if (X and Y) or (not Z):
    return True
else:
    return False
What is the output if X = True, Y = False, and Z = False?


In [64]:

A = True
B = False
C = True

(A and B) or (not C and B)

False

In [65]:
X = False 
Y = True
not(X or not Y) and (X or Y)

True

In [66]:
A = True
B = False
C = True
result = A and (not B or C) and not (B and C)
print(result)

True


### Ml Package(Data Analysis)
### numpy -> numerical python

In [67]:
import numpy as np

In [68]:
#### Generate numbers from 1 to 100
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [69]:
np.arange(41)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40])

In [70]:
np.arange(2,15,2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [71]:
np.arange(100,0,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [73]:
### 50 zeroes
np.zeros(50,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [74]:
np.ones(50,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [76]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [77]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [80]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [85]:
np.random.rand(2,3)

array([[0.07941376, 0.29521257, 0.77113366],
       [0.94663292, 0.72109437, 0.44182352]])

In [87]:
np.random.randn(2,3)

array([[-1.39389564,  0.22650558,  0.30599615],
       [-0.6147777 , -1.87511262, -0.01350352]])

In [91]:
np.random.randint(2,6)

2

In [92]:
np.random.randint(20,78,100)

array([50, 48, 30, 20, 58, 63, 43, 35, 76, 45, 72, 20, 75, 30, 27, 60, 58,
       26, 65, 27, 45, 74, 72, 63, 67, 23, 43, 48, 71, 38, 54, 52, 73, 55,
       75, 77, 70, 75, 59, 40, 21, 33, 52, 54, 60, 20, 57, 29, 71, 20, 40,
       27, 28, 33, 69, 57, 35, 30, 27, 37, 51, 30, 42, 24, 43, 23, 51, 28,
       35, 64, 21, 37, 65, 43, 29, 77, 30, 56, 76, 73, 40, 41, 72, 42, 20,
       70, 26, 27, 55, 31, 21, 66, 28, 69, 69, 66, 61, 69, 28, 61])

In [94]:
### Create an array from 0 to 29

sample=np.arange(0,30)
sample

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [95]:
sample.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [96]:
sample.reshape(4,7)

ValueError: cannot reshape array of size 30 into shape (4,7)

In [97]:
rand_array=np.random.rand(6,7)

In [98]:
rand_array

array([[0.99219676, 0.29553745, 0.76479232, 0.11430524, 0.47010028,
        0.81867772, 0.54674843],
       [0.9888968 , 0.38851664, 0.51676985, 0.67153575, 0.22097116,
        0.39068512, 0.82443896],
       [0.69134354, 0.64114544, 0.34011178, 0.10591391, 0.70405697,
        0.29531944, 0.94028123],
       [0.19969783, 0.42049707, 0.28609599, 0.67561045, 0.93704898,
        0.10790354, 0.43772696],
       [0.1251357 , 0.08983677, 0.43281755, 0.89627309, 0.69632513,
        0.4236894 , 0.45541342],
       [0.99180389, 0.96296451, 0.25644811, 0.51723956, 0.13492175,
        0.12254827, 0.56204487]])

In [99]:
rand_array.max()

0.992196760020129

In [100]:
rand_array.min()

0.0898367680309281

In [101]:
rand_array.T

array([[0.99219676, 0.9888968 , 0.69134354, 0.19969783, 0.1251357 ,
        0.99180389],
       [0.29553745, 0.38851664, 0.64114544, 0.42049707, 0.08983677,
        0.96296451],
       [0.76479232, 0.51676985, 0.34011178, 0.28609599, 0.43281755,
        0.25644811],
       [0.11430524, 0.67153575, 0.10591391, 0.67561045, 0.89627309,
        0.51723956],
       [0.47010028, 0.22097116, 0.70405697, 0.93704898, 0.69632513,
        0.13492175],
       [0.81867772, 0.39068512, 0.29531944, 0.10790354, 0.4236894 ,
        0.12254827],
       [0.54674843, 0.82443896, 0.94028123, 0.43772696, 0.45541342,
        0.56204487]])

In [102]:
### create an array from 10 to 20
sample_array=np.arange(10,21)

In [103]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [104]:
sample_array[0]

10

In [105]:
sample_array[5]

15

In [106]:
sample_array[100]

IndexError: index 100 is out of bounds for axis 0 with size 11

In [107]:
sample_array[0:5]

array([10, 11, 12, 13, 14])

In [108]:
sample_array[0:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [109]:
sample_array[5:]

array([15, 16, 17, 18, 19, 20])

In [110]:
sample_array[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [111]:
sample_array.max()

20

In [112]:
np.max(sample_array)

20

In [113]:
np.min(sample_array)

10

In [114]:
np.square(sample_array)

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400])

In [115]:
np.sqrt(sample_array)

array([3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [116]:
np.log(sample_array)

array([2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227])

In [117]:
np.exp(sample_array)

array([2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
       1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
       6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [118]:
np.mean(sample_array)

15.0

In [119]:
np.median(sample_array)

15.0

In [120]:
np.std(sample_array)

3.1622776601683795

In [121]:
np.var(sample_array)

10.0

In [125]:
rand_array

array([[0.99219676, 0.29553745, 0.76479232, 0.11430524, 0.47010028,
        0.81867772, 0.54674843],
       [0.9888968 , 0.38851664, 0.51676985, 0.67153575, 0.22097116,
        0.39068512, 0.82443896],
       [0.69134354, 0.64114544, 0.34011178, 0.10591391, 0.70405697,
        0.29531944, 0.94028123],
       [0.19969783, 0.42049707, 0.28609599, 0.67561045, 0.93704898,
        0.10790354, 0.43772696],
       [0.1251357 , 0.08983677, 0.43281755, 0.89627309, 0.69632513,
        0.4236894 , 0.45541342],
       [0.99180389, 0.96296451, 0.25644811, 0.51723956, 0.13492175,
        0.12254827, 0.56204487]])

In [126]:
np.round(rand_array,decimals=3)

array([[0.992, 0.296, 0.765, 0.114, 0.47 , 0.819, 0.547],
       [0.989, 0.389, 0.517, 0.672, 0.221, 0.391, 0.824],
       [0.691, 0.641, 0.34 , 0.106, 0.704, 0.295, 0.94 ],
       [0.2  , 0.42 , 0.286, 0.676, 0.937, 0.108, 0.438],
       [0.125, 0.09 , 0.433, 0.896, 0.696, 0.424, 0.455],
       [0.992, 0.963, 0.256, 0.517, 0.135, 0.123, 0.562]])

In [129]:
sample_matrix=np.array([[23,15,27],[16,63,29],[45,67,32]])
sample_matrix

array([[23, 15, 27],
       [16, 63, 29],
       [45, 67, 32]])

In [130]:
sample_matrix[0]

array([23, 15, 27])

In [131]:
sample_matrix[1,2]

29

In [133]:
sample_matrix[2,:]

array([45, 67, 32])

In [134]:
sample_matrix[:,0]

array([23, 16, 45])

In [137]:
sample_matrix[:,(2,1)]

array([[27, 15],
       [29, 63],
       [32, 67]])

In [139]:
np.square(sample_matrix)

array([[ 529,  225,  729],
       [ 256, 3969,  841],
       [2025, 4489, 1024]])

In [140]:
sports=np.array(["golf","cricket","football","Cricket","fball","cricket"])
sports

array(['golf', 'cricket', 'football', 'Cricket', 'fball', 'cricket'],
      dtype='<U8')

In [142]:
sports.unique()

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [147]:
np.unique(sports)

array(['Cricket', 'cricket', 'fball', 'football', 'golf'], dtype='<U8')

In [148]:
np.nunique(sports)

AttributeError: module 'numpy' has no attribute 'nunique'

In [149]:
sports.nunique()

AttributeError: 'numpy.ndarray' object has no attribute 'nunique'

In [150]:
 len(np.unique(sports))

5

### Python Flow Controls

#### Conditional statements

In [151]:
number=8

if number>0:
    print(number,"is greater than zero")

8 is greater than zero


In [155]:
number=0

if number>0:
    print(number,"is greater than zero")

In [156]:
number=-3

if number<0:
    print(number,"is lesser than zero")

-3 is lesser than zero


In [158]:
number=0

if number<0:
    print(number,"is lesser than zero")

In [160]:
number=-5

if number>0:
    print(number,"is greater than zero")
else:
    print(number,"is lesser than zero")

-5 is lesser than zero


In [163]:
number=-5.6

if number>0:
    print(number,"is greater than zero")
else:
    print(number,"is lesser than zero")

-5.6 is lesser than zero


In [168]:
number=0.0

if number>0:
    print(number,"is greater than zero")
elif number==0:
    print(number,"is equal to zero")
else:
    print(number,"is lesser than zero")

0.0 is equal to zero


In [182]:
age=10

if 0<age<=3:
    print("No fare")
elif 3<age<=10:
    print("Entry fee is 20")
elif 10<age<=20:
    print("Entry fee is 25")
else:
    print("Entry fee is 30")

Entry fee is 20


In [186]:
number=-11

if number %2==0:
    print("The given number is even")
else:
    print("The given number is odd")

The given number is odd


In [187]:
a=10
b=12

if a>b:
    print("a is greater than b")
else:
    print("b is greater than a")

b is greater than a


In [ ]:
### Write a program to find whether the person is eligible to vote
### Write a program to check whether the gn char is a vowel or not

In [191]:
char="A"

if char in "aeiouAEIOU":
    print("The character is a vowel")
else:
    print("The character is not a vowel")

The character is a vowel


In [ ]:
### Write a program to check whether the triangle is equilateral,isoceles or scalene triangle
a=20
b=10
c=20
if a==b==c:
    print("Equilateral Triangle")
elif a==b or b==c or a==c:
    print("isoceles triangle")
else:
    print("Scalene")

In [ ]:
a=float(input("Enter first side of the traingle"))
b=float(input("Enter second side of the traingle"))
c=float(input("Enter third side of the traingle"))

if a==b==c:
    print("Equilateral Triangle")
elif a==b or b==c or a==c:
    print("isoceles triangle")
else:
    print("Scalene")

In [194]:
### Write a program to check whether the number is divisible by both 5 and 11

number=44

if number%5==0 and number%11==0:
    print(number," is divisible by both 5 and 11") 
else :
    print(number," is not divisible by both 5 and 11")

44  is not divisible by both 5 and 11


In [198]:
### Check the largest among the three given numbers

number1 = 20 
number2 = 400
number3 = 400

list1 = [number1,number2,number3] 
max(list1)

if number1 > number2 and number1 > number3 :
    print(number1," is the greatest")
elif number2 > number1 and number2 > number3 :
    print(number2," is the greatest") 
else :
    print(number3," is the greatest")

400  is the greatest


In [199]:
### Print 1 2 3 4 5
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [200]:
### Loops
for i in range(1,6):
    print(i)

1
2
3
4
5


In [201]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [202]:
for i in range(1,11,2):
    print(i)

1
3
5
7
9


In [203]:
for i in range(2,51,2):
    print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


In [204]:
for i in range(1,51):
    if i%2==0:
        print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


In [205]:
for i in range(5,61):
    if i %5==0:
        print(i)

5
10
15
20
25
30
35
40
45
50
55
60


In [206]:
for i in range(5,61,5):
      print(i)

5
10
15
20
25
30
35
40
45
50
55
60


In [207]:
for i in range(1,13):
    print(i*5)

5
10
15
20
25
30
35
40
45
50
55
60


In [208]:
np.arange(5,61,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [209]:
### Summation

sum=0
for i in range(1,11):
    sum=sum+i
print(sum)

55


In [210]:
sum=0

for i in range(2,11,2):
    sum=sum+i
print(sum)

30


In [211]:
## print numbers from 1 to 5
for i in range(1,6):
    print(i)

1
2
3
4
5


In [212]:
count=1

while count<=5:
    print(count)
    count+=1

1
2
3
4
5


In [213]:
count=0

while count<3:
    print("hello")
    count+=1

hello
hello
hello


In [214]:
### Print 5 4 3 2 1 using while loop
count=5

while count>=1:
    print(count)
    count-=1

5
4
3
2
1


In [219]:
text="Datascience"

for letter in text:
    if letter=="e":
        break
    print(letter)
    

D
a
t
a
s
c
i


In [218]:
text="Datascience"

for letter in text:
    if letter=="e":
        print("The loop skipped a space here")
        continue
    print(letter)

D
a
t
a
s
c
i
The loop skipped a space here
n
c
The loop skipped a space here


#### Self-Assessment 4:
#### https://github.com/Premalatha-success/TIAA_batch1_nov/blob/main/Worksheet_dict.docx

In [ ]:
Worksheet: Dictionary Hands-On Exercises
1. Create and Access a Dictionary
   - Create a dictionary called `student` with the following key-value pairs:
     Name: 'John Doe'
     Age: 21
     Subjects: ['Math', 'Science', 'History']
   - Access and print:
     - The name of the student.
     - The age of the student.
     - The second subject in the `Subjects` list.

2. Update and Add Items
   - Update the `Age` of the student to 22.
   - Add a new key-value pair: `Grade: 'A'`.
   - Print the updated dictionary.

3. Remove an Item
   - Remove the `Subjects` key from the `student` dictionary.
   - Print the modified dictionary.

4. Iterating Through a Dictionary
   - Using a `for` loop, iterate over the `student` dictionary to print keys and their corresponding values in the format:
     Key: Value

5. Using Dictionary Methods
   - Use the `keys()`, `values()`, and `items()` methods on the `student` dictionary and print the results.

---


6. Nested Dictionaries
   - Create a nested dictionary called `classroom` with the following structure:
     {
         'Student1': {'Name': 'Alice', 'Age': 20, 'Subjects': ['English', 'Biology']},
         'Student2': {'Name': 'Bob', 'Age': 22, 'Subjects': ['Math', 'Chemistry']},
         'Student3': {'Name': 'Charlie', 'Age': 21, 'Subjects': ['History', 'Physics']}
     }
   - Access and print:
     - The name of `Student2`.
     - The subjects of `Student3`.

7. Merge Two Dictionaries
   - Given two dictionaries:
     dict1 = {'a': 1, 'b': 2}
     dict2 = {'b': 3, 'c': 4}
   - Merge them into one dictionary such that if a key exists in both, its value in the resulting dictionary is the sum of the values.
     Expected output:
     {'a': 1, 'b': 5, 'c': 4}

8. i) Check whether “a” in dict 1 as a key
ii) Check whether 4 in dict2 as a value


In [220]:
student={ "Name": 'John Doe',"Age": 21,"Subjects": ['Math', 'Science', 'History']}

In [221]:
student

{'Name': 'John Doe', 'Age': 21, 'Subjects': ['Math', 'Science', 'History']}

In [223]:
student["Name"]

'John Doe'

In [224]:
student["Age"]

21

In [226]:
student["Subjects"][1]

'Science'

In [227]:
student["Age"]=22

In [228]:
student

{'Name': 'John Doe', 'Age': 22, 'Subjects': ['Math', 'Science', 'History']}

In [229]:
student["Grade"]="A"
student

{'Name': 'John Doe',
 'Age': 22,
 'Subjects': ['Math', 'Science', 'History'],
 'Grade': 'A'}

In [230]:
del student["Subjects"]
student

{'Name': 'John Doe', 'Age': 22, 'Grade': 'A'}

In [231]:
for i in student:
    print(f"{i}:{student[i]}")

Name:John Doe
Age:22
Grade:A


In [232]:
student.keys()
student.values()
student.items()

dict_items([('Name', 'John Doe'), ('Age', 22), ('Grade', 'A')])

In [233]:
classroom = {
    'Student1': {'Name': 'Alice', 'Age': 20, 'Subjects': ['English', 'Biology']},
    'Student2': {'Name': 'Bob', 'Age': 22, 'Subjects': ['Math', 'Chemistry']},
    'Student3': {'Name': 'Charlie', 'Age': 21, 'Subjects': ['History', 'Physics']}
}

In [234]:
classroom

{'Student1': {'Name': 'Alice', 'Age': 20, 'Subjects': ['English', 'Biology']},
 'Student2': {'Name': 'Bob', 'Age': 22, 'Subjects': ['Math', 'Chemistry']},
 'Student3': {'Name': 'Charlie',
  'Age': 21,
  'Subjects': ['History', 'Physics']}}

In [235]:
classroom["Student2"]["Name"]

'Bob'

In [237]:
classroom["Student3"]["Subjects"]

['History', 'Physics']

### List Comprehension

In [ ]:
expression for item in iterable if condition

In [1]:
### Print numbers from 1 to 10

for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [2]:
[i for i in range(1,11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
### Square of numbers from 1 to 10
for i in range(1,11):
    print(i**2)

1
4
9
16
25
36
49
64
81
100


In [4]:
[i**2 for i in range(1,11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [5]:
### List of prices->7,1.8,3.4,2.1,98
prices=[7,1.8,3.4,2.1,98]
[item*2 for item in prices]

[14, 3.6, 6.8, 4.2, 196]

In [6]:
sent="NLP is little complicated but sounds interesting"
sent

'NLP is little complicated but sounds interesting'

In [7]:
[vowel for vowel in sent if vowel in "aeiouAEIOU"]

['i', 'i', 'e', 'o', 'i', 'a', 'e', 'u', 'o', 'u', 'i', 'e', 'e', 'i']

In [8]:
#### Try to print the consonants from the above sent
[cons for cons in sent if cons not in "aeiouAEIOU"]

['N',
 'L',
 'P',
 ' ',
 's',
 ' ',
 'l',
 't',
 't',
 'l',
 ' ',
 'c',
 'm',
 'p',
 'l',
 'c',
 't',
 'd',
 ' ',
 'b',
 't',
 ' ',
 's',
 'n',
 'd',
 's',
 ' ',
 'n',
 't',
 'r',
 's',
 't',
 'n',
 'g']

In [9]:
[x for x in range(1,21) if x%2==0]

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [10]:
[x for x in range(1,21) if x%2!=0]

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [11]:
list1=["hello","world","python","programs"]
[x.upper() for x in list1]

['HELLO', 'WORLD', 'PYTHON', 'PROGRAMS']

In [12]:
list2=[-21,24,-0.6,-98,98,0]
[x for x in list2 if x>0]


[24, 98]

In [14]:
tuple(i for i in range(1,11))

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [15]:
### expected o/p->[odd,even,odd,even,...]
["even" if x%2==0 else "odd" for x in range(1,11)]

['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even']

In [18]:
### To find the maximum of three numbers
a=100
b=200
c=30
[a if a > b and a > c else b if b > c else c]

[200]

In [20]:
list3=["apple","mango","oranges","banana","Cherries"]
[x for x in list3 if len(x)>5]

['oranges', 'banana', 'Cherries']

In [ ]:
### Functions
def functionname() parameters

In [21]:
def add(num1,num2):
    addition=num1+num2
    return addition

In [22]:
add(3,5)

8

In [24]:
def add_1(num1,num2):
    print("Number 1:",num1)
    print("Number 2:",num2)
    addition=num1+num2
    return addition

In [25]:
add_1(5,6)

Number 1: 5
Number 2: 6


11

In [26]:
def say_hello():
    print("Hello Python")

In [27]:
say_hello()

Hello Python


In [28]:
def greeting(name):
    print("hello %s" %name)

In [29]:
greeting("Python")

hello Python


In [30]:
def greet(name):
    print("hello",name,"welcome")

In [31]:
person_name="Latha"
greet(person_name)

hello Latha welcome


In [32]:
greet()

TypeError: greet() missing 1 required positional argument: 'name'

In [33]:
def employee(Name,Designation):
    print(Name,Designation)

In [34]:
employee(Name="Latha",Designation="Trainer")
employee(Designation="Trainer",Name="Latha")

Latha Trainer
Latha Trainer


In [35]:
def emp(name,sal=50000):
    print("emp_name",name)
    print("emp_salary",sal)

In [36]:
emp("John")

emp_name John
emp_salary 50000


In [37]:
emp("lucky")

emp_name lucky
emp_salary 50000


In [38]:
### Write program to find whether the number is even
def is_even(num):
    return num%2==0


In [39]:
is_even(6)

True

In [40]:
is_even(5)

False

In [41]:
### Greater among two numbers

def greater(num1,num2):
    if num1>num2:
        return num1
    else:
        return num2

In [42]:
greater(6,7)

7

In [43]:
greater(11,7)

11

In [ ]:
lambda arguments:expression

In [45]:
add=lambda a,b:a+b

In [46]:
add(5,6)

11

In [47]:
square=lambda x:x**2
square(15)

225

In [ ]:
def greater(num1,num2):
    if num1>num2:
        return num1
    else:
        return num2

In [48]:
maximum=lambda x,y:x if x>y else y
maximum(10,15)

15

In [50]:
even_odd=lambda x:"Even" if x%2==0 else "odd"
even_odd(10)

'Even'

In [51]:
lenString = lambda x: len(x)
lenString("Hello")

5

In [54]:
numbers=[6,18,21,13,10,8,4,3]
even=list(filter(lambda x:x%2==0,numbers))

In [55]:
even

[6, 18, 10, 8, 4]

In [56]:
list1=list(range(1,11))
list(filter(lambda x:x%5==0,list1))

[5, 10]

In [57]:
list2=list(range(1,11))
list(map(lambda x:x**2,list2))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [61]:
from functools import reduce

In [62]:
num_list=[1,2,3,4,5]
reduce(lambda a,b:a*b,num_list)

120

### Sets

In [5]:
mySet = {1,2,2,3,4,5,6,7}
print(mySet)

{1, 2, 3, 4, 5, 6, 7}


In [6]:
for ele in mySet:
  print(ele)

1
2
3
4
5
6
7


In [7]:
mySet.add("Three")
mySet

{1, 2, 3, 4, 5, 6, 7, 'Three'}

In [8]:
myNewSet = {"aaa","bbb","ccc"}
mySet.update(myNewSet)

In [9]:
mySet

{1, 2, 3, 4, 5, 6, 7, 'Three', 'aaa', 'bbb', 'ccc'}

In [10]:
mySet.remove("aaa")


In [11]:
mySet

{1, 2, 3, 4, 5, 6, 7, 'Three', 'bbb', 'ccc'}

In [12]:
len(mySet)

10

In [13]:
fruits = {"Apple","Organge","Banana","Tomato"}
vegetable = {"Carrot","Mango","Tomato"}

In [14]:
fruits.add("Papaya")
fruits

{'Apple', 'Banana', 'Organge', 'Papaya', 'Tomato'}

In [15]:
fruits.difference(vegetable)

{'Apple', 'Banana', 'Organge', 'Papaya'}

In [16]:
fruits = {"Apple","Organge","Banana","Tomato"}
vegetable = {"Carrot","Mango","Tomato"}
intersectionSet = fruits.intersection(vegetable)
print(intersectionSet)

{'Tomato'}


In [17]:
fruits = {"Apple","Organge","Banana","Tomato"}

print("Looping set using foreach - ")
for items in fruits:
  print(items)

Looping set using foreach - 
Apple
Organge
Banana
Tomato


In [4]:
a = 1
b = int(input("Enter the value: "))

try:
  # logic where the exception causes
  a = a/b

except ZeroDivisionError:
  print(f"The number you provided can't divide {a} because it is {b}")

except ValueError:
  print(f"{b} provided input is invalid")

except:
  print("Something went wrong")
  
else:
  print(f"Success the division value: {a}")

finally:
  print("Execution finished")

Enter the value:  2


Success the division value: 0.5
Execution finished


### sql with Python

In [5]:
!pip install mysql-connector-python

In [6]:
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="Syn"
)

cursor = connection.cursor()

In [8]:
# Example query
cursor.execute("SELECT * FROM mytable")
for row in cursor.fetchall():
    print(row)

connection.close()

(1, 'Alice', 26)
(2, 'Bob', 30)


In [18]:
import re


In [22]:
text = "Hello, welcome to Python programming."
pattern = r"\bPython\b"

match = re.search(pattern, text)
if match:
    print("Found:", match.group())


Found: Python


In [22]:
text = "The sky is blue."
pattern = "blue"
replacement = "clear"

new_text = re.sub(pattern, replacement, text)
print(new_text)  # Output: The sky is clear.


The sky is clear.


In [16]:
pattern = re.compile(r"\d+")
text1 = "Order number 12345"
text2 = "Invoice 67890"

match1 = pattern.search(text1)
match2 = pattern.search(text2)

if match1 and match2:
    print("First match:", match1.group())
    print("Second match:", match2.group())


First match: 12345
Second match: 67890


In [26]:
pattern = r"Hi"
text = "Hi Hello, world!"

match = re.match(pattern, text)
if match:
    print("Match at the start:", match.group())


Match at the start: Hi


In [18]:
pattern = r"world"
text = "Hello, world!"

match = re.search(pattern, text)
if match:
    print("Found:", match.group())


Found: world


In [19]:
pattern = r"\d{3}-\d{2}-\d{4}"
text = "My number is 123-45-6789."

match = re.search(pattern, text)
if match:
    print("Found SSN:", match.group())


Found SSN: 123-45-6789


In [30]:
pattern = r"(\b\w+)\s+\1"
text = "This is is a a atest."

match = re.search(pattern, text)
if match:
    print("Repeated word:", match.group(1))


Repeated word: is


In [23]:
text = "Hello, world!"
translation_table = str.maketrans("aeiou", "12345")  

translated_text = text.translate(translation_table)
print(translated_text) 


H2ll4, w4rld!


In [11]:
### Sets:

myset={1,2,7,2,19,5,21.5,4,500,100,123.4,"apple","orange","python","hi","Apple","HI"}
myset

{1,
 100,
 123.4,
 19,
 2,
 21.5,
 4,
 5,
 500,
 7,
 'Apple',
 'HI',
 'apple',
 'hi',
 'orange',
 'python'}

In [12]:
myset.add(12)

In [13]:
myset

{1,
 100,
 12,
 123.4,
 19,
 2,
 21.5,
 4,
 5,
 500,
 7,
 'Apple',
 'HI',
 'apple',
 'hi',
 'orange',
 'python'}

In [14]:
myset.append(12)

AttributeError: 'set' object has no attribute 'append'

In [15]:
myset.remove(19)

In [16]:
myset

{1,
 100,
 12,
 123.4,
 2,
 21.5,
 4,
 5,
 500,
 7,
 'Apple',
 'HI',
 'apple',
 'hi',
 'orange',
 'python'}

In [17]:
myset[0]="hi"

TypeError: 'set' object does not support item assignment